version: "3.8"

volumes:
  db-volume:

networks:
  default:

services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-33060}:3306
    volumes:
      - db-volume:/var/lib/mysql
    env_file: ./docker.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-express}
      MYSQL_USER: ${DB_USERNAME:-express}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks:
      - default

  app:
    image: node:14-alpine
    env_file: ./docker.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - ${APP_PORT:-8080}:80
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    networks:
      - default
    depends_on:
      - db
